version: "3.3"
services:
  #gatewayAPI:
  #  image: "apache/apisix"
  #  ports:
  #    - "9080:9080"
  #  environment:
  #    - APISIX_STAND_ALONE=true

  etcd:
    image: "bitnami/etcd:latest"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://127.0.0.1:2379

  gatewayAPI-dashboard:
    image: "apache/apisix-dashboard"
    ports:
      - "9080:9080"
      - "9091:9091"
      #      - "2379:2379"
      - "9000:9000"
